"use client";

import Link from "next/link";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { useStory } from "@/lib/story-context";
import { PlaceHolderImages } from "@/lib/placeholder-images";
import { ArrowRight, BookCopy, PenSquare } from "lucide-react";

export default function Home() {
  const { stories } = useStory();
  const heroImage = PlaceHolderImages.find(img => img.id === "hero-background");

  return (
    <div className="flex flex-col min-h-[calc(100vh-3.5rem)]">
      <section className="relative w-full py-20 md:py-32 lg:py-40 flex items-center justify-center text-center">
        {heroImage && (
          <Image
            src={heroImage.imageUrl}
            alt={heroImage.description}
            fill
            className="object-cover"
            data-ai-hint={heroImage.imageHint}
            priority
          />
        )}
        <div className="absolute inset-0 bg-background/50" />
        <div className="container relative px-4 md:px-6">
          <div className="max-w-3xl mx-auto">
            <h1 className="text-4xl font-headline font-bold tracking-tighter sm:text-5xl md:text-6xl text-foreground">
              Branching Narratives
            </h1>
            <p className="mt-4 text-foreground/80 md:text-xl">
              Craft your own adventure. Every choice carves a new path in an ever-evolving story, generated by AI.
            </p>
            <div className="mt-6 flex flex-col gap-4 sm:flex-row justify-center">
              <Button size="lg" asChild>
                <Link href="/create">
                  <PenSquare className="mr-2 h-5 w-5" />
                  Create a New Story
                </Link>
              </Button>
            </div>
          </div>
        </div>
      </section>

      <section className="w-full py-12 md:py-24 lg:py-32 bg-secondary/50">
        <div className="container px-4 md:px-6">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <h2 className="text-3xl font-headline font-bold tracking-tighter sm:text-5xl">Your Story Library</h2>
              <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                {stories.length > 0 ? "Continue your adventures or start a new one." : "Your created stories will appear here. Let's create your first!"}
              </p>
            </div>
          </div>
          {stories.length > 0 ? (
            <div className="mx-auto grid max-w-5xl grid-cols-1 gap-6 py-12 sm:grid-cols-2 lg:grid-cols-3">
              {stories.map((story) => (
                <Card key={story.id} className="hover:shadow-lg transition-shadow">
                  <CardHeader>
                    <CardTitle className="font-headline flex items-center gap-2">
                      <BookCopy className="w-5 h-5 text-primary" />
                      {story.title}
                    </CardTitle>
                    <CardDescription>Genre: {story.genre}</CardDescription>
                  </CardHeader>
                  <CardContent>
                    <p className="text-sm text-muted-foreground mb-4">
                      {Object.keys(story.nodes).length} parts explored.
                    </p>
                    <Button asChild variant="outline" className="w-full">
                      <Link href={`/story/${story.id}`}>
                        Continue Story <ArrowRight className="ml-2 h-4 w-4" />
                      </Link>
                    </Button>
                  </CardContent>
                </Card>
              ))}
            </div>
          ) : (
            <div className="text-center py-12">
               <p className="text-muted-foreground">No stories yet.</p>
            </div>
          )}
        </div>
      </section>
    </div>
  );
}
